default: &default
  adapter: postgresql
  encoding: utf8

development:
  <<: *default
  url: <%= ENV['DEV_DATABASE_URL'] %>
  # DEV_DATABASE_URL=postgres://pub-web-app:pub-web-app@localhost/pub-web-app-dev

test:
  <<: *default
  url: <%= ENV['TEST_DATABASE_URL'] %>

production:
  <<: *default
  url: <%= ENV['PROD_DATABASE_URL'] %>
